apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  namespace: ns-todo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo-todo
          image: mongo
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-volume
              mountPath: /data/db
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
      volumes: 
        - name: mongo-volume
          persistentVolumeClaim:
            claimName: mongo-pvc