apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
  namespace: ns-todo
spec:
  resources:
    requests:
      storage: 20Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce