apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-todo
  namespace: ns-todo
data:
  appsettings.json: |
    {
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft.AspNetCore": "Warning"
        }
      },
      "AllowedHosts": "*",
      "MongoDb": {
        "ConnectionString": "mongodb://mongo-service:27017/toDo",
        "DatabaseName": "toDo"
      },
      "OpenTelemetry": {
        "Url": "http://otel-collector:4317"
      }
    }

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-api
  namespace: ns-todo
  labels:
    app: todo-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-api
  template:
    metadata:
      labels:
        app: todo-api
    spec:
      hostname: todo-api 
      volumes:
      - name: appsettings-volume
        configMap:
          name: cm-todo
          items:
          - key: appsettings.json
            path: appsettings.json
      containers:
      - name: todo-api
        image: todo-api
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        volumeMounts:
        - name: appsettings-volume
          mountPath: /app/appsettings.json
          subPath: appsettings.json
        resources:
          requests:
            memory: "64Mi"
            cpu: "10m"
          limits:
            memory: "128Mi"
            cpu: "200m"

---

apiVersion: v1
kind: Service
metadata:
  name: todo-api-service
  namespace: ns-todo
spec:
  selector:
    app: todo-api
  type: NodePort
  ports:
  - port: 8080
    targetPort: 80
    protocol: TCP
    name: http

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: todo-api-hpa
  namespace: ns-todo
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: todo-api
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 90
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 90
